package jks.card.model;

public enum Enum_Event 
{
	// PASSIVE EFFECT
	TURN_END,
	TURN_START,
	PLAYER_LOSE_HP,
	PLAYER_GAIN_HP,
	
	// ACTIVE EFFECT
	MONSTER_ENTER_BATTLEFIELD,
	MONSTER_LEAVE_BATTLEFIELD, 
	MONSTER_ATTACK,
	MONSTER_GET_ATTACK,
	ENERGY_SPENT, 
}
